ShopGiay/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ShopGiay.Models;

namespace ShopGiay.Controllers
{
    public class ProductAdminController : Controller
    {
        private Data db = new Data();

        // GET: ProductAdmin
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Account).Include(p => p.ProductCategory);
            return View(products.ToList());
        }

        // GET: ProductAdmin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: ProductAdmin/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username");
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: ProductAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Price,Quantity,UserId,CategoryId,Descripsion,Image")] Product product, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem có bất kỳ sản phẩm nào trong cơ sở dữ liệu có cùng Name không
                bool isDuplicateName = db.Products.Any(p => p.Name == product.Name);

                if (isDuplicateName)
                {
                    ModelState.AddModelError("Name", "Product name already exists. Please choose another name.");
                }
                else if (imageFile != null && imageFile.ContentLength > 0)
                {
                    // Lưu tên tệp tin hình ảnh
                    string fileName = Path.GetFileName(imageFile.FileName);

                    // Lưu tệp tin hình ảnh vào thư mục
                    string imagePath = Path.Combine(Server.MapPath("~/Public/image/"), fileName);
                    imageFile.SaveAs(imagePath);

                    // Lưu đường dẫn của hình ảnh vào cơ sở dữ liệu
                    product.Image = fileName;


                    // Tạo số ngẫu nhiên
                    Random random = new Random();
                    int randomNumber = random.Next(1000, 9999);
                    //Tạo productId 
                    product.ProductId = $"msp{randomNumber}";

                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {


                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: ProductAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: ProductAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra tên sản phẩm trùng lặp
                if (db.Products.Any(p => p.Name == product.Name && p.ProductId != product.ProductId))
                {
                    ModelState.AddModelError("Name", "Product name already exists.");
                    return View("Edit", product);
                }

                // Kiểm tra tệp tin ảnh đã tải lên
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    // Xóa tệp tin ảnh cũ (nếu tồn tại)
                    string oldImagePath = Server.MapPath("~/Public/image/" + product.Image);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                    // Lưu tệp tin ảnh mới
                    string extension = Path.GetExtension(imageFile.FileName);
                    string newImageName = Guid.NewGuid().ToString() + extension;
                    string newImagePath = Server.MapPath("~/Public/image/" + newImageName);
                    imageFile.SaveAs(newImagePath);

                    // Cập nhật đường dẫn ảnh mới trong sản phẩm
                    product.Image = newImageName;
                }

                // Lưu sản phẩm vào cơ sở dữ liệu
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // Load UserId và CategoryId để hiển thị trong dropdownlist
            ViewBag.UserId = new SelectList(db.Accounts, "Id", "Name", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "Id", "Name", product.CategoryId);
            return View("Edit", product);
        }


        // GET: ProductAdmin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopGiay/Controllers/ProductCategoriesAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopGiay.Models;

namespace ShopGiay.Controllers
{
    public class ProductCategoriesAdminController : Controller
    {
        private Data db = new Data();

        // GET: ProductCategoriesAdmin
        public ActionResult Index()
        {
            var list = db.ProductCategories.ToList();
            return View("Index", list);
        }

        // GET: ProductCategoriesAdmin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // GET: ProductCategoriesAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCategoriesAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryName")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem có loại sản phẩm có cùng Name đã tồn tại trong cơ sở dữ liệu hay không
                var existingCategory = db.ProductCategories.FirstOrDefault(c => c.CategoryName == productCategory.CategoryName);
                if (existingCategory != null)
                {
                    ModelState.AddModelError("", "The product type name already exists.");
                    return View(productCategory);
                }

                // Tạo số ngẫu nhiên
                Random random = new Random();
                int randomNumber = random.Next(1000, 9999);


                // Gán productcategoryId ngẫu nhiên
                productCategory.CategoryId = $"madanhmuc{randomNumber}";

                db.ProductCategories.Add(productCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productCategory);
        }

        // GET: ProductCategoriesAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategoriesAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryName")] ProductCategory productCategory)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem có loại sản phẩm khác có cùng tên đã tồn tại trong cơ sở dữ liệu hay không
                var existingCategory = db.ProductCategories.FirstOrDefault(c => c.CategoryName == productCategory.CategoryName);
                if (existingCategory != null)
                {
                    ModelState.AddModelError("", " The product type name already exists.");
                    return View(productCategory);
                }

                db.Entry(productCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productCategory);
        }

        // GET: ProductCategoriesAdmin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }
            return View(productCategory);
        }

        // POST: ProductCategoriesAdmin/DeleteConfirmed/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ProductCategory productCategory = db.ProductCategories.Find(id);
            if (productCategory == null)
            {
                return HttpNotFound();
            }

            // Xóa các bản ghi liên quan trong bảng "Products"
            var products = db.Products.Where(p => p.CategoryId == id).ToList();
            db.Products.RemoveRange(products);

            db.ProductCategories.Remove(productCategory);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ShopGiay/Views/ProductCategoriesAdmin/Create.cshtml
@model ShopGiay.Models.ProductCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Card formatting */
    .card {
        margin-top: 20px;
        background-color: #ffffff;
        border: 1px solid #dee2e6;
        border-radius: 5px;
    }

    /* Card header styling */
    .card-header {
        font-size: 1.2rem;
        font-weight: bold;
    }

    /* Button size */
    .btn-success {
        margin-left: 5px;
    }

    /* Form formatting */
    .form-horizontal {
        margin-top: 20px;
    }

    /* Label and input field formatting */
    .control-label {
        font-weight: bold;
    }

    /* Input field formatting */
    .form-control {
        width: 100%;
    }

    /* Warning alert */
    .alert-warning {
        margin-top: 20px;
    }

    /* Footer note */
    .footer {
        margin-top: 20px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Add Product Category</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "ProductCategoriesAdmin")" class="btn btn-sm btn-success">
                        <i class="fas fa-arrow-left"></i>Back to List
                    </a>
                    <button type="submit" class="btn-sm btn btn-success">
                        <i class="fas fa-save"></i>Save[Add]
                    </button>
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="alert alert-warning">
                <strong>Notice: </strong> Do you want to add this category?
            </div>
            <div class="form-horizontal">
                <h4>Product Category</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ShopGiay/Views/ProductCategoriesAdmin/Delete.cshtml
@model ShopGiay.Models.ProductCategory

@{
    ViewBag.Title = "DeleteConfirmed";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Card formatting */
    .card {
        margin-top: 20px;
        background-color: #ffffff;
        border: 1px solid #dee2e6;
        border-radius: 5px;
    }

    /* Card header styling */
    .card-header {
        font-size: 1.2rem;
        font-weight: bold;
    }

    /* Button size */
    .btn-success {
        margin-left: 5px;
    }

    /* Detailed information table formatting */
    dl {
        margin-top: 20px;
        font-size: 1rem;
    }

    /* Detailed information table cell formatting */
    dt, dd {
        padding: 8px;
        border-bottom: 1px solid #dee2e6;
    }

    /* Footer styling */
    .footer {
        margin-top: 20px;
    }

    /* Alert formatting */
    .alert {
        margin-top: 10px;
    }

    /* Delete confirmation button */
    .my-2 {
        margin-top: 10px;
    }
</style>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Confirm Category Deletion</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Index", "ProductCategoriesAdmin")" class="btn btn-sm btn-success">
                    <i class="fas fa-arrow-left"></i> Back to the List
                </a>
                @using (Html.BeginForm("DeleteConfirmed", "ProductCategoriesAdmin", new { id = Model.CategoryId }, FormMethod.Post, new { @class = "my-2" }))
                {
                    @Html.AntiForgeryToken()
                    <input type="submit" value="Delete" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete?')" />
                }
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        @if (!string.IsNullOrEmpty(TempData["ErrorMessage"] as string))
        {
            <div class="alert alert-danger">
                @TempData["ErrorMessage"]
            </div>
        }
        @if (!string.IsNullOrEmpty(TempData["SuccessMessage"] as string))
        {
            <div class="alert alert-success">
                @TempData["SuccessMessage"]
            </div>
        }
        <div class="alert alert-warning">
            <strong>Notification:</strong> Are you sure you want to delete the category?
        </div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.CategoryId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CategoryId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.CategoryName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.CategoryName)
            </dd>
        </dl>
    </div>
</div>

ShopGiay/Views/ProductCategoriesAdmin/Details.cshtml
@model ShopGiay.Models.ProductCategory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Card formatting */
    .card {
        margin-top: 20px;
        background-color: #fff;
        border: 1px solid #dee2e6;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    /* Card header styling */
    .card-header {
        font-size: 1.5rem;
        font-weight: bold;
        background-color: #f8f9fa;
        padding: 10px;
        border-bottom: 1px solid #dee2e6;
        border-radius: 5px 5px 0 0;
    }

    /* Button size */
    .btn-success {
        margin-left: 10px;
    }

    /* Detailed information table formatting */
    table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
    }

    /* Detailed information table cell formatting */
    td {
        padding: 12px;
        border-bottom: 1px solid #dee2e6;
    }

    /* Footer note formatting */
    .footer {
        margin-top: 20px;
        font-size: 0.8rem;
        color: #6c757d;
    }
</style>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Product</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Index", "ProductAdmin")" class="btn btn-sm btn-success">
                    <i class="fas fa-arrow-left"></i>Back to List
                </a>
                <a href="@Url.Action("Edit", "ProductAdmin", new { id = Model.Products} )" class="btn btn-sm btn-success">
                    <i class="fas fa-save"></i>Edit
                </a>
            </div>
        </div>
    </div>
    <table>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.CategoryId)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.CategoryId)
            </td>
        </tr>
        <tr>
            <td>
                <b>@Html.DisplayNameFor(model => model.CategoryName)</b>
            </td>
            <td>
                @Html.DisplayFor(model => model.CategoryName)
            </td>
        </tr>
    </table>
</div>

ShopGiay/Views/ProductCategoriesAdmin/Edit.cshtml
@model ShopGiay.Models.ProductCategory

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Card formatting */
    .card {
        margin-top: 20px;
        background-color: #ffffff;
        border: 1px solid #dee2e6;
        border-radius: 5px;
    }

    /* Card header styling */
    .card-header {
        font-size: 1.2rem;
        font-weight: bold;
    }

    /* Button size */
    .btn-success,
    .btn-danger {
        margin-left: 5px;
    }

    /* Alert box formatting */
    .alert-warning {
        margin-top: 20px;
    }

    /* Input field group formatting */
    .form-group {
        margin-top: 15px;
    }

    /* Label for input field formatting */
    .control-label {
        font-weight: bold;
    }

    /* Input field formatting */
    .form-control {
        width: 100%;
        padding: 8px;
        border-radius: 5px;
        border: 1px solid #ced4da;
    }

    /* Footer note formatting */
    .footer {
        margin-top: 20px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-md-6">
                    <strong class="text-uppercase text-danger">Confirm Product Category Edit</strong>
                </div>
                <div class="col-md-6 text-end">
                    <a href="@Url.Action("Index", "ProductCategoriesAdmin")" class="btn btn-sm btn-success">
                        <i class="fas fa-arrow-left"></i>Back to List
                    </a>
                    <input type="submit" value="Edit" class="btn btn-sm btn-danger" />
                </div>
            </div>
        </div>
        <div class="card-body p-3">
            <div class="alert alert-warning">
                <strong>Notice: </strong> Are you sure you want to edit?
            </div>
            <div class="form-horizontal">
                <h4>Product Category</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CategoryId)

                <div class="form-group">
                    @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                        @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ShopGiay/Views/ProductCategoriesAdmin/Index.cshtml
@model IEnumerable<ShopGiay.Models.ProductCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    /* Card formatting */
    .card {
        margin-top: 20px;
        background-color: #ffffff;
        border: 1px solid #dee2e6;
        border-radius: 5px;
    }

    /* Card header styling */
    .card-header {
        font-size: 1.2rem;
        font-weight: bold;
    }

    /* Button size */
    .btn-success {
        margin-left: 5px;
    }

    /* Product category list table */
    .table {
        margin-top: 10px;
    }

    /* Header formatting for the table */
    th, td {
        text-align: center;
    }

    /* Checkbox styling */
    input[name="checkId"] {
        width: 16px;
        height: 16px;
    }

    /* Feature formatting */
    .btn-info, .btn-warning, .btn-danger {
        margin: 0 3px;
    }
</style>
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger ">Product Categories List</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create", "ProductCategoriesAdmin")" class="btn btn-sm btn-success">
                    <i class="fas fa-plus"></i>Add
                </a>
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-center">Category ID</th>
                    <th>Category Name</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.CategoryId</td>
                        <td>@item.CategoryName</td>
                        <td class="text-center">
                            <a href="@Url.Action("Edit", "ProductCategoriesAdmin" , new { @id = item.CategoryId})" class="btn btn-sm btn-info">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="@Url.Action("Details", "ProductCategoriesAdmin" , new { @id = item.CategoryId})" class="btn btn-sm btn-warning">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="@Url.Action("Delete", "ProductCategoriesAdmin" , new { @id = item.CategoryId})" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>