ShopGiay/Controllers/AccountManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShopGiay.Models;

namespace ShopGiay.Controllers
{
    public class AccountManagementController : Controller
    {
        private Data db = new Data();

        // GET: AccountManagement
        public ActionResult Index()
        {
            return View(db.Accounts.ToList());
        }

        // GET: AccountManagement/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: AccountManagement/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Username,Password,Role")] Account account)
        {
            // Kiểm tra xem UserId đã tồn tại hay chưa
            if (db.Accounts.Any(a => a.UserId == account.UserId))
            {
                ModelState.AddModelError("UserId", "UserId already exists.");
            }

            if (ModelState.IsValid)
            {

                account.UserId = "IDUs" + account.Role + account.Username;
                db.Accounts.Add(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: AccountManagement/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: AccountManagement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,Username,Password,Role")] Account updatedAccount)
        {
            if (ModelState.IsValid)
            {
                // Find the existing account in the database
                var existingAccount = db.Accounts.Find(updatedAccount.UserId);

                if (existingAccount == null)
                {
                    return HttpNotFound(); // or handle the situation where the account is not found
                }

                // Update properties of the existing account
                existingAccount.Username = updatedAccount.Username;
                existingAccount.Password = updatedAccount.Password;
                existingAccount.Role = updatedAccount.Role;

                // Save changes to the database
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // If ModelState is not valid, return to the Edit view with the model
            return View(updatedAccount);
        }

        // GET: AccountManagement/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: AccountManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            // Xóa các bản ghi liên quan trong bảng "Product"
            var products = db.Products.Where(p => p.UserId == id).ToList();
            db.Products.RemoveRange(products);

            // Xóa các bản ghi liên quan trong bảng "Cart"
            var carts = db.Carts.Where(c => c.UserId == id).ToList();
            db.Carts.RemoveRange(carts);
            // Xóa các bản ghi liên quan trong bảng "InforAccount"
            var inforAccounts = db.InforAccounts.Where(i => i.UserId == id).ToList();
            db.InforAccounts.RemoveRange(inforAccounts);

            // Xóa tài khoản
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            db.Accounts.Remove(account);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopGiay/Controllers/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ShopGiay.Models;

namespace ShopGiay.Controllers
{
    public class ProductAdminController : Controller
    {
        private Data db = new Data();

        // GET: ProductAdmin
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Account).Include(p => p.ProductCategory);
            return View(products.ToList());
        }

        // GET: ProductAdmin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: ProductAdmin/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username");
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName");
            return View();
        }

        // POST: ProductAdmin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Price,Quantity,UserId,CategoryId,Descripsion,Image")] Product product, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra xem có bất kỳ sản phẩm nào trong cơ sở dữ liệu có cùng Name không
                bool isDuplicateName = db.Products.Any(p => p.Name == product.Name);

                if (isDuplicateName)
                {
                    ModelState.AddModelError("Name", "Product name already exists. Please choose another name.");
                }
                else if (imageFile != null && imageFile.ContentLength > 0)
                {
                    // Lưu tên tệp tin hình ảnh
                    string fileName = Path.GetFileName(imageFile.FileName);

                    // Lưu tệp tin hình ảnh vào thư mục
                    string imagePath = Path.Combine(Server.MapPath("~/Public/image/"), fileName);
                    imageFile.SaveAs(imagePath);

                    // Lưu đường dẫn của hình ảnh vào cơ sở dữ liệu
                    product.Image = fileName;


                    // Tạo số ngẫu nhiên
                    Random random = new Random();
                    int randomNumber = random.Next(1000, 9999);
                    //Tạo productId 
                    product.ProductId = $"msp{randomNumber}";

                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {


                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // GET: ProductAdmin/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Accounts, "UserId", "Username", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "CategoryId", "CategoryName", product.CategoryId);
            return View(product);
        }

        // POST: ProductAdmin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, HttpPostedFileBase imageFile)
        {
            if (ModelState.IsValid)
            {
                // Kiểm tra tên sản phẩm trùng lặp
                if (db.Products.Any(p => p.Name == product.Name && p.ProductId != product.ProductId))
                {
                    ModelState.AddModelError("Name", "Product name already exists.");
                    return View("Edit", product);
                }

                // Kiểm tra tệp tin ảnh đã tải lên
                if (imageFile != null && imageFile.ContentLength > 0)
                {
                    // Xóa tệp tin ảnh cũ (nếu tồn tại)
                    string oldImagePath = Server.MapPath("~/Public/image/" + product.Image);
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                    // Lưu tệp tin ảnh mới
                    string extension = Path.GetExtension(imageFile.FileName);
                    string newImageName = Guid.NewGuid().ToString() + extension;
                    string newImagePath = Server.MapPath("~/Public/image/" + newImageName);
                    imageFile.SaveAs(newImagePath);

                    // Cập nhật đường dẫn ảnh mới trong sản phẩm
                    product.Image = newImageName;
                }

                // Lưu sản phẩm vào cơ sở dữ liệu
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            // Load UserId và CategoryId để hiển thị trong dropdownlist
            ViewBag.UserId = new SelectList(db.Accounts, "Id", "Name", product.UserId);
            ViewBag.CategoryId = new SelectList(db.ProductCategories, "Id", "Name", product.CategoryId);
            return View("Edit", product);
        }


        // GET: ProductAdmin/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShopGiay/Controllers/ProductController.cs
using ShopGiay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace ShopGiay.Controllers
{
    public class ProductController : Controller
    {
        private Data db = new Data();

        // GET: Product
        public ActionResult Index()
        {
            var account = db.Products.ToList();
            return View(account);
        }
        public ActionResult ProductDetails(string productId)
        {
            // Lấy thông tin sản phẩm từ cơ sở dữ liệu hoặc từ nguồn dữ liệu khác
            var product = db.Products.FirstOrDefault(p => p.ProductId == productId);

            // Kiểm tra xem sản phẩm có tồn tại không
            if (product == null)
            {
                // Nếu không tồn tại, có thể chuyển hướng hoặc xử lý theo ý muốn
                return HttpNotFound(); // Trả về mã lỗi 404 Not Found
            }

            // Chuyển dữ liệu sản phẩm đến view để hiển thị
            return View(product);
        }
        [HttpGet]
        public ActionResult Search(string searchText)
        {
            if (string.IsNullOrEmpty(searchText))
            {
                return RedirectToAction("Index", "Home");
            }

            var searchResults = db.Products
                .Where(p => p.Name.ToLower().Contains(searchText.ToLower()))
                .ToList();

            return View(searchResults);
        }

    }
}

ShopGiay/Controllers/ReportsController.cs
using ShopGiay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ShopGiay.Controllers
{
    public class ReportsController : Controller
    {
        private Data db = new Data();
        // GET: Reports
        public ActionResult Index()
        {
            double? totalRevenue = db.Orders.Sum(o => o.TotalPrice);
            int totalItemsSold = db.Orders.Count();
            var orders = db.Orders.ToList(); // Lấy danh sách các đối tượng Order từ cơ sở dữ liệu

            ViewBag.TotalRevenue = totalRevenue ?? 0;
            ViewBag.TotalItemsSold = totalItemsSold != null ? totalItemsSold : 0;

            return View(orders); // Truyền danh sách Order vào view
        }

        public ActionResult DeleteOrder() {
            return View();
        }
        [HttpPost]
        public ActionResult DeleteOrder(string orderId)
        {
            if (orderId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            // Tìm hóa đơn cần xóa trong cơ sở dữ liệu
            var order = db.Orders.Find(orderId);

            if (order == null)
            {
                return HttpNotFound();
            }

            // Xóa hóa đơn khỏi cơ sở dữ liệu
            db.Orders.Remove(order);
            db.SaveChanges();

            

            // Chuyển hướng về trang danh sách hóa đơn (hoặc trang tương tự)
            return RedirectToAction("Index");
        }


    }
}

ShopGiay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Shop Shoes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="d-flex align-items-center">
                <div class="d-flex align-items-center">
                    @using (Html.BeginForm("Search", "Product", FormMethod.Get))
                    {
                        <div class="input-group">
                            <input type="text" name="searchText" class="form-control" placeholder="Search">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">
                                    <i class="bi bi-search"></i>
                                </button>
                            </div>
                        </div>
                    }
                </div>

                <ul class="navbar-nav flex-grow-1 ml-auto">
                    <li><a href="@Url.Action("InforAccount", "Account")" class="nav-link text-white"><i class="bi bi-person mr-3"></i></a></li>
                    <li><a href="@Url.Action("Index", "Cart")" class="nav-link text-white"><i class="bi bi-cart mr-3"></i></a></li>
                    <li><a href="@Url.Action("Logout", "Account")" class="nav-link text-white"><i class="bi bi-box-arrow-right"></i></a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Shop Shoes</p>
            <p>Liên hệ : nhom11@gmail.com</p>
            <p>Địa chỉ : Sinh viên trường đại học Quy Nhơn</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- Bootstrap JS and Popper.js (required for Bootstrap) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

</body>
</html>

ShopGiay/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>@Page.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Public/css/LayoutAdmin.css" rel="stylesheet" />
    <link href="~/Public/css/all.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script>
        // Define the logout function
        function logout() {
            // Perform logout operations here
            // Example: redirect to the login page
            window.location.href = '@Url.Action("Logout", "Account")';
        }
    </script>
    @RenderSection("head", required: false)
    <style>
        .navbar-nav .logout-link {
            color: #fff;
            cursor: pointer;
        }

        body {
            background-color: #f8f9fa; /* Page background color */
            font-family: 'Roboto', sans-serif;
        }

        .header {
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000; /* Use a higher z-index to make sure it appears above other content */
            background-color: #53a879 !important; /* Header background color */
        }

            .header a.navbar-brand {
                font-size: 1.5rem;
                font-weight: bold;
            }

        .navbar-toggler-icon {
            background-color: #fff; /* Toggle icon color */
        }

        .navbar-nav .nav-link {
            color: #fff; /* Menu text color */
        }

        .navbar-nav .nav-item.dropdown:hover .dropdown-menu {
            display: block; /* Display dropdown menu on hover */
        }

        .maincontent {
            min-height: 100vh;
            background-color: #fff; /* Main content background color */
            border: 1px solid #ddd; /* Main content border */
            border-radius: 8px; /* Rounded corners */
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Shadow */
            margin-top: 20px; /* Top margin */
            padding: 20px; /* Inner padding */
        }

        .footer {
            width: 100%;
            background-color: #53a879 !important; /* Footer background color */
            color: #fff; /* Footer text color */
            padding: 15px 0; /* Footer padding */
        }
    </style>
</head>

<body>
    <section class="clearfix header">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="@Url.Action("Index", "Reports")">Admin Management</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Products
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "ProductAdmin")">Product List</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "ProductCategoriesAdmin")">Category List</a></li>
                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Customer Accounts
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("Index", "AccountManagement")">Customer Account List</a></li>
                                </ul>
                            </li>
                            <li class="nav-item" style="position: absolute; right: 0;">
                                <a class="nav-link logout-link" onclick="logout()">
                                    <i class="fas fa-sign-out-alt"></i> Logout
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>
        </div>
    </section>

    <section class="clearfix maincontent">
        <div class="container-fluid py-5">
            @RenderBody()
        </div>
    </section>

    <section class="clearfix footer">
        <div class="container-fluid text-white text-center py-1">
            <p>Copyright 2024</p>
        </div>
    </section>

    @RenderSection("footer", required: false)

</body>

</html>